# Generated by Django 6.0.1 on 2026-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
